name: CI/CD for React App

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: my-react-app
      DOCKER_REPO: moltresinnovations
      AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          TAG=$(date +%Y%m%d%H%M%S)
          docker build -t ${DOCKER_USERNAME}/${IMAGE_NAME}:${TAG} my-react-app
          docker push ${DOCKER_USERNAME}/${IMAGE_NAME}:${TAG}
          echo "IMAGE_TAG=${TAG}" >> $GITHUB_ENV

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
             IMAGE_NAME=${{ env.IMAGE_NAME }}
             IMAGE_TAG=${{ env.IMAGE_TAG }}
             DOCKER_USERNAME=${{ env.DOCKER_USERNAME }}

             docker pull ${DOCKER_USERNAME}/$IMAGE_NAME}:${IMAGE_TAG}
             docker stop react-app || true
             docker rm react-app || true
             docker run -d --name react-app -p 81:80 ${DOCKER_USERNAME}/${IMAGE_NAME}:${IMAGE_TAG}
